# Generated by Django 3.1.1 on 2022-12-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221226_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='AGE',
            field=models.IntegerField(null=32),
            preserve_default=32,
        ),
    ]
