# Generated by Django 3.1.1 on 2022-12-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='EMP_ID',
            field=models.CharField(help_text='reference number', max_length=20, primary_key=True, serialize=False),
        ),
    ]
